CREATE DATABASE IF NOT EXISTS PXDevWebSiteV3;
USE PXDevWebSiteV3;
CREATE TABLE IF NOT EXISTS users (
    user_id INT PRIMARY KEY AUTO_INCREMENT,
    username VARCHAR(50) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);
CREATE TABLE IF NOT EXISTS visitors (
    visitor_id INT PRIMARY KEY AUTO_INCREMENT,
    visit_date DATETIME DEFAULT CURRENT_TIMESTAMP,
    visitor_ip VARCHAR(45),
    user_id INT NULL,
    FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE
    SET NULL,
        INDEX (user_id),
        INDEX (visitor_ip)
);