import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TUGER",
  description: "Generated by create next app",
};

import Footer from "@/components/footer/Footer";
import { SupportProvider } from "@/context/SupportContext";
import { CartProvider } from "@/context/CartContext";
import { CartAnimationProvider } from "@/context/CartAnimationContext";
import { Toaster } from "react-hot-toast";
import SupportWidget from "@/components/support/SupportWidget";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <CartProvider>
          <CartAnimationProvider>
            <SupportProvider>
              {children}
              <SupportWidget />
            </SupportProvider>
          </CartAnimationProvider>
          <Toaster 
            position="top-right" 
            toastOptions={{
              style: {
                background: "#0c1022",
                color: "#fff",
                border: "1px solid rgba(255, 255, 255, 0.1)",
                borderRadius: "1rem",
              }
            }} 
          />
        </CartProvider>
      </body>
    </html>
  );
}

