import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TUGER",
  description: "Generated by create next app",
};

import Footer from "@/components/footer/Footer";
import { SupportProvider } from "@/context/SupportContext";
import { CartProvider } from "@/context/CartContext";
import { CartAnimationProvider } from "@/context/CartAnimationContext";
import { CategoryMenuProvider } from "@/context/CategoryMenuContext";
import { Toaster } from "react-hot-toast";
import SupportWidget from "@/components/support/SupportWidget";
import { getSettings } from "@/lib/actions/settings-actions";
import { getSession } from "@/lib/auth";
import MaintenanceScreen from "@/components/MaintenanceScreen";
import { getFeatureFlag } from "@/lib/feature-flags";

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const settings = await getSettings();
  const session = await getSession().catch(() => null);
  const isAdmin = session?.user?.role === "ADMIN";
  const inMaintenance = !!settings?.maintenanceMode && !isAdmin;
  const aiChatEnabled = await getFeatureFlag("ai_chat_assistant", true);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {inMaintenance ? (
          <MaintenanceScreen message={settings?.maintenanceMessage} />
        ) : (
          <CartProvider>
            <CartAnimationProvider>
              <CategoryMenuProvider>
                <SupportProvider>
                  {children}
                  <SupportWidget aiChatEnabled={aiChatEnabled} />
                </SupportProvider>
              </CategoryMenuProvider>
            </CartAnimationProvider>
            <Toaster
              position="top-right"
              toastOptions={{
                style: {
                  background: "#0c1022",
                  color: "#fff",
                  border: "1px solid rgba(255, 255, 255, 0.1)",
                  borderRadius: "1rem",
                }
              }}
            />
          </CartProvider>
        )}
      </body>
    </html>
  );
}

