import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "TUGER",
  description: "Generated by create next app",
};

import Footer from "@/components/footer/Footer";
import { SupportProvider } from "@/context/SupportContext";
import SupportWidget from "@/components/support/SupportWidget";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <SupportProvider>
          {children}
          <SupportWidget />
        </SupportProvider>
        <Footer />
      </body>
    </html>
  );
}
